# Generated by Django 5.2.12 on 2026-03-27 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAttempt',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('answer', models.JSONField(default=dict)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Ожидает'),
                            ('running', 'Выполняется'),
                            ('success', 'Успешно'),
                            ('failure', 'Ошибка'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('output', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'fragment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attempts',
                        to='courses.fragment',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='task_attempts',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
