FROM python:3.13
RUN apt-get update && apt-get install -y docker.io && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src /src
EXPOSE 8080
WORKDIR /src

CMD ["fastapi", "run", "app.py", "--port", "8080"]
